baseurl = "http://naelawayes.github.io"
title = "Nael AWAYES"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Développeur C/CPP/Swift/Web Full Stack<!--]--><br /><!--[--><!--]-->'
  copyright = "Nael AWAYES"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "#"

[languages]
[languages.fr]
languageName = "English"
weight = 1
