baseurl = "http://naelawayes.github.io"
title = "Nael AWAYES"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Développeur C/CPP/Swift/Web Full Stack<!--]--><br /><!--[--><!--]-->'
  copyright = "Nael AWAYES"

[[params.social]]
  medium = "GitHub"
  icon = "github"
  link = "https://github.com/NaelAwayes"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/naelawayes/"

[[params.social]]
  medium = "CV"
  icon = "file-pdf-o"
  link = "/documents/CV_Nael_AWAYES_AVRIL_2018_FR_4x4.pdf"

[languages]
[languages.fr]
languageName = "English"
weight = 1
